{% set name = "drf-flex-fields" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/drf-flex-fields-{{ version }}.tar.gz
  sha256: 48139eeff0b1232fc05a9f353c3c2b570b225985043dedda6ab0d5e8b7a1d7af

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  #imports:
  #  - rest_flex_fields
  commands:
    - pip check
    # We cannot import-test here as it requires a fully-specified django configuration.
    - test -f $SP_DIR/rest_flex_fields/__init__.py
  requires:
    - pip

about:
  home: https://github.com/rsinger86/drf-flex-fields
  summary: Flexible, dynamic fields and nested resources for Django REST Framework serializers.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
